Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using Swaed.Models;

namespace Swaed.Controllers
{
    public class EventController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddEvent()
        {
            return View();

        }


        // ADD NEW EVENTS
        [HttpPost]
        public async Task<IActionResult> AddEvent(Event model)
        {
            if (!ModelState.IsValid)
            {

            }
            return View("Index");
        }

        [HttpGet]
        public async Task<IActionResult> FindEvent(string id)
        {
            return View("Index");
        }
    }

}

Controllers/OpportunityController.cs
using Microsoft.AspNetCore.Mvc;
using Swaed.Models;

namespace Swaed.Controllers
{
    public class OpportunityController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Opportunity model)
        {
            if (!ModelState.IsValid)
            {

            }
            return View("Index");
        }
    }
}

Controllers/OrganizationController.cs
using Microsoft.AspNetCore.Mvc;

namespace Swaed.Controllers
{
    public class OrganizationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/TrainingController.cs
using Microsoft.AspNetCore.Mvc;
using Swaed.Models;

namespace Swaed.Controllers
{
    public class TrainingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Training model)
        {
            if (!ModelState.IsValid)
            {

            }
            return View("Index");
        }
    }
}

Views/Shared/_Footer.cshtml
<!--====================  patners begin ====================-->
<div class="client-carousel @@extraClassName">
    <div class="container">
        <!-- Mettez ici le contenu de votre carousel de partenaires -->
    </div>
</div>
<!-- /.patner end -->
<footer class="main-footer">
    <div class="main-footer__bg" style="background-image: url(~/assets/images/shapes/footer-bg-1.png);"></div>
    <div class="container">
        <!-- Mettez ici le contenu de votre footer -->
    </div><!-- /.container -->
</footer><!-- /.main-footer -->

<section class="copyright text-center">
    <div class="container wow fadeInUp" data-wow-delay="400ms">
        <p class="copyright__text">Copyright <span class="dynamic-year"></span><!-- /.dynamic-year --> | swaed UAE. All Rights Reserved</p>
    </div><!-- /.container -->
</section><!-- /.copyright -->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Swaed</title>
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/Swaed.styles.css" asp-append-version="true" />

    <!-- Mettre en place vos balises meta, liens de style, scripts, etc. -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/assets/images/favicons/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="~/assets/images/favicons/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="~/assets/images/favicons/favicon-16x16.png" />
    <link rel="manifest" href="~/assets/images/favicons/site.webmanifest" />
    <meta name="description" content="Eduact HTML Template For Educaton & LMS" />

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Water+Brush&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/assets/vendors/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/assets/vendors/bootstrap-select/bootstrap-select.min.css" />
    <link rel="stylesheet" href="~/assets/vendors/jquery-ui/jquery-ui.css" />
    <link rel="stylesheet" href="~/assets/vendors/animate/animate.min.css" />
    <link rel="stylesheet" href="~/assets/vendors/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/assets/vendors/eduact-icons/style.css" />
    <link rel="stylesheet" href="~/assets/vendors/jarallax/jarallax.css" />
    <link rel="stylesheet" href="~/assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css" />
    <link rel="stylesheet" href="~/assets/vendors/nouislider/nouislider.min.css" />
    <link rel="stylesheet" href="~/assets/vendors/nouislider/nouislider.pips.css" />
    <link rel="stylesheet" href="~/assets/vendors/odometer/odometer.min.css" />
    <link rel="stylesheet" href="~/assets/vendors/tiny-slider/tiny-slider.min.css" />
    <link rel="stylesheet" href="~/assets/vendors/owl-carousel/assets/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/assets/vendors/owl-carousel/assets/owl.theme.default.min.css" />

    <!-- template styles -->
    <link rel="stylesheet" href="~/assets/css/eduact.css" />
    <!-- Boxicons CSS -->
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <style>
        /* Custom styles for the modal */
        .modal-header {
            border-bottom: none;
        }

        .modal-body {
            font-size: 1.1em;
        }

        .modal-footer {
            border-top: none;
        }

        .modal-content {
            border-radius: 10px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.3);
        }

        .btn-close-custom {
            background: none;
            border: none;
            font-size: 1.5em;
            line-height: 1;
            color: #000;
            opacity: 0.5;
        }

            .btn-close-custom:hover {
                opacity: 1;
            }
    </style>
</head>
<body>
    @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Swaed</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@
    <header class="main-header">
        <div class="preloader">
            <div class="preloader__image" style="background-image: url(assets/images/loader.png);"></div>
        </div>
        <nav class="main-menu">
            <div class="container">
                <div class="main-menu__logo">
                    <a asp-area="" asp-page="/">
                        <img src="~/assets/images/logo3.png" width="110" height="70" alt="Eduact">
                    </a>
                </div>
                <div class="main-menu__nav">
                    <ul class="main-menu__list">
                        <li> <a asp-area="" asp-page="/">Home</a></li>
                        <li> <a asp-area="" asp-page="/About">About Us</a></li>
                        <li> <a asp-area="" asp-page="/Opportunities">Opportunities</a></li>
                        <li> <a asp-area="" asp-page="/Gallery">Gallery</a></li>
                        <li> <a asp-area="" asp-page="/Contact">Contact Us</a></li>
                        <li> <a asp-controller="Organization" asp-action="Index">Organisation</a></li>
                        <li> <a asp-controller="Event" asp-action="AddEvent">Add Event </a></li>
                    </ul>
                </div>
                <div class="main-menu__right">
                    <a asp-area="" asp-controller="Account" asp-action="Login" class="eduact-btn"><span class="eduact-btn__curve"></span><i class="icon-account-1"></i>Login</a>
                </div>
            </div>
        </nav>
    </header>
            @RenderBody()
    <section class="cta-one-space"></section>

    <!-- Modal -->
    <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="messageModalLabel"></h5>
                    <button type="button" class="btn-close-custom" data-dismiss="modal" aria-label="Close">
                        &times;
                    </button>
                </div>
                <div class="modal-body" id="messageModalBody"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

   
    <!-- Inclure le footer -->
    @Html.Partial("_Footer")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- scripts -->
    <script src="~/assets/vendors/jquery/jquery-3.5.1.min.js"></script>
    <script src="~/assets/vendors/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendors/bootstrap-select/bootstrap-select.min.js"></script>
    <script src="~/assets/vendors/jquery-ui/jquery-ui.js"></script>
    <script src="~/assets/vendors/jarallax/jarallax.min.js"></script>
    <script src="~/assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js"></script>
    <script src="~/assets/vendors/jquery-appear/jquery.appear.min.js"></script>
    <script src="~/assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js"></script>
    <script src="~/assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js"></script>
    <script src="~/assets/vendors/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/assets/vendors/nouislider/nouislider.min.js"></script>
    <script src="~/assets/vendors/odometer/odometer.min.js"></script>
    <script src="~/assets/vendors/tiny-slider/tiny-slider.min.js"></script>
    <script src="~/assets/vendors/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/assets/vendors/wnumb/wNumb.min.js"></script>
    <script src="~/assets/vendors/jquery-circleType/jquery.circleType.js"></script>
    <script src="~/assets/vendors/jquery-lettering/jquery.lettering.min.js"></script>
    <script src="~/assets/vendors/tilt/tilt.jquery.js"></script>
    <script src="~/assets/vendors/wow/wow.js"></script>
    <script src="~/assets/vendors/isotope/isotope.js"></script>
    <script src="~/assets/vendors/countdown/countdown.min.js"></script>
    <!-- template js -->
    <script src="~/assets/js/eduact.js"></script>

    <script src="~/assets/js/bootstrap-multiselect.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#exampleModal").modal("show");
            var successMessage = '@TempData["SuccessMessage"]';
            var errorMessage = '@TempData["ErrorMessage"]';

            // if (successMessage) {
            //     toastr.success(successMessage);
            // }

            // if (errorMessage) {
            //     toastr.error(errorMessage);
            // }

            if (successMessage) {
                showMessageModal('Success', successMessage, 'success');
            }

            if (errorMessage) {
                showMessageModal('Error', errorMessage, 'error');
            }
        });

        function showMessageModal(title, message, type) {
            $('#messageModalLabel').text(title);
            $('#messageModalBody').text(message);

            if (type === 'success') {
                $('#messageModalLabel').addClass('text-success');
            } else if (type === 'error') {
                $('#messageModalLabel').addClass('text-danger');
            }

            $('#messageModal').modal('show');
        }

        // Votre JavaScript personnalisé ici
        // Assurez-vous d'ajuster les chemins d'accès des éléments selon votre structure de projet
        // Par exemple:
        // $("#image-picker").change(function (event) {
        //     readURL(this);
        // });

        // function readURL(input) {
        //     if (input.files && input.files[0]) {
        //         var reader = new FileReader();

        //         reader.onload = function (e) {
        //             $('#image-preview').attr('src', e.target.result);
        //         }

        //         reader.readAsDataURL(input.files[0]);
        //     }
        // }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_OrgFooterLayout.cshtml
<!--begin::Javascript-->
<script>var hostUrl = "@Url.Content("~/assets/")";</script>
<!--begin::Global Javascript Bundle(mandatory for all pages)-->
<script src="@Url.Content("~/assets/plugins/global/plugins.bundle.js")"></script>
<script src="@Url.Content("~/assets/js/scripts.bundle.js")"></script>
<!--end::Global Javascript Bundle-->
<!--begin::Vendors Javascript(used for this page only)-->
<script src="@Url.Content("~/assets/plugins/custom/fullcalendar/fullcalendar.bundle.js")"></script>
<script src="https://cdn.amcharts.com/lib/5/index.js"></script>
<script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
<script src="https://cdn.amcharts.com/lib/5/percent.js"></script>
<script src="https://cdn.amcharts.com/lib/5/radar.js"></script>
<script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
<script src="https://cdn.amcharts.com/lib/5/map.js"></script>
<script src="https://cdn.amcharts.com/lib/5/geodata/worldLow.js"></script>
<script src="https://cdn.amcharts.com/lib/5/geodata/continentsLow.js"></script>
<script src="https://cdn.amcharts.com/lib/5/geodata/usaLow.js"></script>
<script src="https://cdn.amcharts.com/lib/5/geodata/worldTimeZonesLow.js"></script>
<script src="https://cdn.amcharts.com/lib/5/geodata/worldTimeZoneAreasLow.js"></script>
<script src="@Url.Content("~/assets/plugins/custom/datatables/datatables.bundle.js")"></script>
<!--end::Vendors Javascript-->
<!--begin::Custom Javascript(used for this page only)-->
<script src="@Url.Content("~/assets/js/widgets.bundle.js")"></script>
<script src="@Url.Content("~/assets/js/custom/widgets.js")"></script>
<script src="@Url.Content("~/assets/js/custom/apps/chat/chat.js")"></script>
<script src="@Url.Content("~/assets/js/custom/utilities/modals/users-search.js")"></script>
<!--end::Custom Javascript-->
<!--end::Javascript-->
<script>
    ClassicEditor
        .create(document.querySelector('#editor'))
        .catch(error => {
            console.error(error);
        });
    ClassicEditor
        .create(document.querySelector('#editor2'))
        .catch(error => {
            console.error(error);
        });
</script>

Views/Shared/_OrgHeaderLayout.cshtml
<title>Swaed</title>
<meta charset="utf-8" />
<meta name="description" content="The most advanced Bootstrap 5 Admin Theme with 40 unique prebuilt layouts on Themeforest trusted by 100,000 beginners and professionals. Multi-demo, Dark Mode, RTL support and complete React, Angular, Vue, Asp.Net Core, Rails, Spring, Blazor, Django, Express.js, Node.js, Flask, Symfony & Laravel versions. Grab your copy now and get life-time updates for free." />
<meta name="keywords" content="metronic, bootstrap, bootstrap 5, angular, VueJs, React, Asp.Net Core, Rails, Spring, Blazor, Django, Express.js, Node.js, Flask, Symfony & Laravel starter kits, admin themes, web design, figma, web development, free templates, free admin themes, bootstrap theme, bootstrap template, bootstrap dashboard, bootstrap dak mode, bootstrap button, bootstrap datepicker, bootstrap timepicker, fullcalendar, datatables, flaticon" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="article" />
<meta property="og:title" content="Metronic - The World's #1 Selling Bootstrap Admin Template - Metronic by KeenThemes" />
<meta property="og:url" content="https://keenthemes.com/metronic" />
<meta property="og:site_name" content="Metronic by Keenthemes" />
<link rel="canonical" href="https://preview.keenthemes.com/metronic8" />

<!--begin::Fonts(mandatory for all pages)-->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
<!--end::Fonts-->
<!--begin::Vendor Stylesheets(used for this page only)-->
<link href="~/assets/plugins/custom/fullcalendar/fullcalendar.bundle.css" rel="stylesheet" type="text/css" />
<link href="~/assets/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />

<!--begin::Global Stylesheets Bundle(mandatory for all pages)-->
<link href="~/assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
<link href="~/assets/css/style.css" rel="stylesheet" type="text/css" />
@* <link href="~/assets/css/swaed.css" rel="stylesheet" type="text/css" /> *@
<!--end::Global Stylesheets Bundle-->
<script src="https://cdn.ckeditor.com/ckeditor5/41.2.1/classic/ckeditor.js"></script>

Views/Shared/_OrgSidBarLayout.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>



@* Début du menu latéral *@
<div class="aside-menu flex-column-fluid">
    <!--begin::Aside Menu-->
    <div class="hover-scroll-overlay-y mx-3 my-5 my-lg-5" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-height="auto" data-kt-scroll-dependencies="{default: '#kt_aside_toolbar, #kt_aside_footer', lg: '#kt_header, #kt_aside_toolbar, #kt_aside_footer'}" data-kt-scroll-wrappers="#kt_aside_menu" data-kt-scroll-offset="5px">
        <!--begin::Menu-->
        <div class="menu menu-column menu-title-gray-800 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-500" data-kt-menu="true">
            <!--begin:Menu item-->
            <div class="menu-item here show menu-accordion" data-kt-menu-trigger="click">
                <!--begin:Menu link-->
                <span class="menu-link">
                    <span class="menu-icon">
                        <i class="ki-duotone ki-element-11 fs-2">
                            <span class="path1"></span>
                            <span class="path2"></span>
                            <span class="path3"></span>
                            <span class="path4"></span>
                        </i>
                    </span>
                    <span class="menu-title">Dashboards</span>
                    <span class="menu-arrow"></span>
                </span>
                <!--end:Menu link-->
                <!--begin:Menu sub-->
                <div class="menu-sub menu-sub-accordion">
                    <!--begin:Menu item-->
                    <div class="menu-item">
                        <!--begin:Menu link-->
                        <a class="menu-link active" href="index.html">
                            <span class="menu-bullet">
                                <span class="bullet bullet-dot"></span>
                            </span>
                            <span class="menu-title">Default</span>
                        </a>
                        <!--end:Menu link-->
                    </div>
                    <!--end:Menu item-->
                </div>
                <!--end:Menu sub-->
            </div>
            <!--end:Menu item-->
            <!--begin:Menu item-->
            <div class="menu-item pt-5">
                <!--begin:Menu content-->
                <div class="menu-content">
                    <span class="menu-heading fw-bold text-uppercase fs-7">Pages</span>
                </div>
                <!--end:Menu content-->
            </div>
            <!--end:Menu item-->
            <!--begin:Menu item-->
            <div class="menu-item menu-lg-down-accordion menu-sub-lg-down-indention" data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="right-start">
                <!--begin:Menu link-->
                <a class="" data-kt-menu-placement="right-start" data-bs-toggle="collapse" href="#collapseExample1" role="button" aria-expanded="false" aria-controls="collapseExample">
                    <span class="menu-link">
                        <span class="menu-icon">
                            <i class="ki-duotone ki-file fs-2">
                                <span class="path1"></span>
                                <span class="path2"></span>
                            </i>
                        </span>
                        <span class="menu-title">Opportunities</span>
                        <span class="menu-arrow"></span>
                    </span>
                </a>
                <div class="collapse" id="collapseExample1">
                    @* <div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown px-2 py-4 w-200px mh-75 overflow-auto"> *@
                    <!--begin:Menu item-->
                    <div class="menu-item">
                        <!--begin:Menu link-->
                        <a class="menu-link" href="@Url.Action("Index", "Opportunity")">
                            <span class="menu-bullet">
                                <span class="bullet bullet-dot"></span>
                            </span>
                            <span class="menu-title">All Opportunities</span>
                        </a>
                        <!--end:Menu link-->
                    </div>
                    <!--end:Menu item-->
                    <!--begin:Menu item-->
                    <div class="menu-item">
                        <!--begin:Menu link-->
                        <a class="menu-link" href="@Url.Action("Create", "Opportunity")">
                            <span class="menu-bullet">
                                <span class="bullet bullet-dot"></span>
                            </span>
                            <span class="menu-title">Create New</span>
                        </a>
                        <!--end:Menu link-->
                    </div>
                    <!--end:Menu item-->
                </div>
            </div>
            <div class="menu-item menu-lg-down-accordion menu-sub-lg-down-indention" data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="right-start">
                <!--begin:Menu link-->
                <a class="" data-kt-menu-placement="right-start" data-bs-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample">
                    <span class="menu-link">
                        <span class="menu-icon">
                            <i class="ki-duotone ki-file fs-2">
                                <span class="path1"></span>
                                <span class="path2"></span>
                            </i>
                        </span>
                        <span class="menu-title">Trainings</span>
                        <span class="menu-arrow"></span>
                    </span>
                </a>
                <div class="collapse" id="collapseExample2">
                    @* <div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown px-2 py-4 w-200px mh-75 overflow-auto"> *@
                    <!--begin:Menu item-->
                    <div class="menu-item">
                        <!--begin:Menu link-->
                        <a class="menu-link" href="@Url.Action("Index", "Training")">
                            <span class="menu-bullet">
                                <span class="bullet bullet-dot"></span>
                            </span>
                            <span class="menu-title">All Trainings</span>
                        </a>
                        <!--end:Menu link-->
                    </div>
                    <!--end:Menu item-->
                    <!--begin:Menu item-->
                    <div class="menu-item">
                        <!--begin:Menu link-->
                        <a class="menu-link" href="@Url.Action("Create", "Trainings")">
                            <span class="menu-bullet">
                                <span class="bullet bullet-dot"></span>
                            </span>
                            <span class="menu-title">Create New</span>
                        </a>
                        <!--end:Menu link-->
                    </div>
                    <!--end:Menu item-->
                </div>
            </div>
            <div class="menu-item menu-lg-down-accordion menu-sub-lg-down-indention" data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="right-start">
                <!--begin:Menu link-->
                <a class="" data-kt-menu-placement="right-start" data-bs-toggle="collapse" href="#collapseExample3" role="button" aria-expanded="false" aria-controls="collapseExample">
                    <span class="menu-link">
                        <span class="menu-icon">
                            <i class="ki-duotone ki-file fs-2">
                                <span class="path1"></span>
                                <span class="path2"></span>
                            </i>
                        </span>
                        <span class="menu-title">Certificates</span>
                        <span class="menu-arrow"></span>
                    </span>
                </a>
                <div class="collapse" id="collapseExample3">
                    @* <div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown px-2 py-4 w-200px mh-75 overflow-auto"> *@
                    <!--begin:Menu item-->
                    <div class="menu-item">
                        <!--begin:Menu link-->
                        <a class="menu-link" href="@Url.Action("ListOpportunity", "Opportunities")">
                            <span class="menu-bullet">
                                <span class="bullet bullet-dot"></span>
                            </span>
                            <span class="menu-title">All Certificates</span>
                        </a>
                        <!--end:Menu link-->
                    </div>
                    <!--end:Menu item-->
                    <!--begin:Menu item-->
                    <div class="menu-item">
                        <!--begin:Menu link-->
                        <a class="menu-link" href="@Url.Action("CreateOpportunity", "Opportunities")">
                            <span class="menu-bullet">
                                <span class="bullet bullet-dot"></span>
                            </span>
                            <span class="menu-title">Create New</span>
                        </a>
                        <!--end:Menu link-->
                    </div>
                    <!--end:Menu item-->
                </div>
            </div>
        </div>
    </div>
    

</div>
<!--end:Menu item-->
<!--begin:Menu item-->
<div class="menu-item pt-5">
    <!--begin:Menu content-->
    <div class="menu-content">
        <span class="menu-heading fw-bold text-uppercase fs-7">Help</span>
    </div>
    <!--end:Menu content-->
</div>
<!--end:Menu item-->
<!--begin:Menu item-->
<div class="menu-item">
    <!--begin:Menu link-->
    <a class="menu-link" href="https://preview.keenthemes.com/html/metronic/docs/base/utilities" target="_blank">
        <span class="menu-icon">
            <i class="ki-duotone ki-rocket fs-2">
                <span class="path1"></span>
                <span class="path2"></span>
            </i>
        </span>
        <span class="menu-title">Admin Management</span>
    </a>
    <!--end:Menu link -->
</div>
<!--end:Menu item-->
<!--begin:Menu item-->
<div class="menu-item">
    <!--begin:Menu link-->
    <a class="menu-link" href="https://preview.keenthemes.com/html/metronic/docs" target="_blank">
        <span class="menu-icon">
            <i class="ki-duotone ki-abstract-26 fs-2">
                <span class="path1"></span>
                <span class="path2"></span>
            </i>
        </span>
        <span class="menu-title">Log Out</span>
    </a>
    <!--end:Menu link-->
</div>
<!--end:Menu item-->
        </div>
<!--end::Menu-->
    </div>
<!--end::Aside Menu-->
</div>
@* Fin du menu latéral *@